---
- name: "Set Up Logging stack"
  hosts: localhost
  gather_facts: yes
  vars_prompt:

    - name: efk_helm_chart_path
      prompt: "Please enter path to efk helm chart"
      default: "/Users/shubhamkawane/Desktop/Advance_Cloud/helm-chart-efk/efk-chart"
      private: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
  roles:
  - setup_logging_stack
  

