---
- name: "Create Kubernetes Cluster"
  hosts: localhost
  gather_facts: yes

  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
  roles:
  - kafka_teardown  

