---
- name: copy nginx default
  template:
    src: "{{ srcpath }}"
    dest: "{{ destpath }}"
    owner: ubuntu
    group: ubuntu
    mode: '0666'
  notify: restart nginx

- name: Create certbot certificate
  command: certbot --nginx -d "{{ domain }}" -m "{{ email }}" --agree-tos --redirect --eff-email
  when: 1 == 1
  notify: restart nginx

- name: Install Docker
  apt:
    name: docker.io

- name: Install Maven
  apt:
    name: maven

- name: Start Docker
  shell: systemctl start docker

- name: Automate Docker
  shell: systemctl enable docker

- name: Add jenkins user to docker group
  user:
    name: jenkins
    group: docker
    append: yes    

- name: Modify Docker Socket File Permission
  file:
    path: /var/run/docker.sock
    mode: '666'

- name: Get helm
  shell: cd /var && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3

- name: Modify Docker Socket File Permission
  file:
    path: /var/get_helm.sh
    mode: '700'

- name: Install helm
  shell: cd /var && ./get_helm.sh

- name: Check File Exists
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_pswd

- debug:
    msg:
    - "Jenkins Password Is: '{{ jenkins_pswd.stdout }}'"
  when: jenkins_pswd.stdout is defined


